# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the workflow will run
on:
  push:
    branches: [ main, prod ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      - name: Git setup
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: cd ./ClientApp; npm install;

      - name: Run unit tests with coverage
        run: cd ./ClientApp; npx jest --coverage;

      - name: Archive zip coverage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./ClientApp/coverage/
